// Package scraper implements the two-phase Bible crawl using Colly.
//
// Phase 1 — setupBooks: writes all book rows and localized titles to the DB
// directly from the JSON spec (no HTTP requests). The number of books is driven
// entirely by the spec files generated by cmd/spec-builder.
//
// Phase 2 — crawlChapters: concurrently fetches every chapter page in both
// Chinese (和合本) and English (BBE) and persists each verse. Verse counts are
// bounded by the per-language spec to handle versification differences
// (cases where CUV and BBE draw chapter boundaries differently).
package scraper

import (
	"fmt"
	"log"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"

	"bible-crawler/internal/config"
	"bible-crawler/internal/repository"
	"bible-crawler/internal/spec"
	"bible-crawler/internal/utils"

	"github.com/PuerkitoBio/goquery"
	"github.com/gocolly/colly/v2"
	"github.com/google/uuid"
)

const (
	// LangChinese is the language key used in DB rows and Colly context.
	LangChinese = "chinese"
	// LangEnglish is the language key used in DB rows and Colly context.
	LangEnglish = "english"
)

// BibleScraper holds the repository, Colly collector, Bible spec, and runtime
// configuration. All crawl parameters (URLs, timeouts, concurrency) come from
// the config so that nothing is hard-coded in application logic.
type BibleScraper struct {
	Repo             *repository.BibleRepository
	C                *colly.Collector
	Spec             *spec.BibleSpec
	Cfg              *config.Config
	globalChapStarts []int
}

// BookMeta keeps the minimal per-book data needed for phase 2.
type BookMeta struct {
	ID    uuid.UUID
	Index int // 0-based index into spec slices
}

// NewBibleScraper initializes a Colly collector with settings from cfg and
// attaches the Bible spec. bibleSpec must have been populated by cmd/spec-builder
// before this is called.
func NewBibleScraper(repo *repository.BibleRepository, bibleSpec *spec.BibleSpec, cfg *config.Config) *BibleScraper {
	c := colly.NewCollector(
		// Restrict crawling to the configured source domain so accidental
		// off-domain redirects are rejected rather than followed.
		colly.AllowedDomains(cfg.SourceDomain),
		colly.UserAgent("Mozilla/5.0 (compatible; BibleCrawler/1.0; +http://yourdomain.com)"),
		colly.Async(true),
		// AllowURLRevisit is needed because the same global chapter index
		// is visited twice (once for ZH, once for EN) with different contexts.
		colly.AllowURLRevisit(),
	)

	// Rate limiting — all values are read from config so operators can tune
	// behaviour via .env without recompiling.
	c.Limit(&colly.LimitRule{
		DomainGlob:  "*" + cfg.SourceDomain + "*",
		Parallelism: cfg.CrawlerParallelism,
		Delay:       time.Duration(cfg.CrawlerDelayMS) * time.Millisecond,
		RandomDelay: time.Duration(cfg.CrawlerRandomDelayMS) * time.Millisecond,
	})

	return &BibleScraper{
		Repo:             repo,
		C:                c,
		Spec:             bibleSpec,
		Cfg:              cfg,
		globalChapStarts: bibleSpec.GlobalChapStarts(),
	}
}

// Run executes the two crawler phases.
// Phase 1 writes book metadata from the JSON spec (no HTTP requests needed).
// Phase 2 crawls every chapter page in both languages and persists verses.
func (s *BibleScraper) Run() error {
	log.Println("Starting Bible Scraper...")
	books, err := s.setupBooks()
	if err != nil {
		return fmt.Errorf("phase 1 failed: %w", err)
	}
	s.crawlChapters(books)
	return nil
}

// setupBooks uses the JSON spec to ensure all book rows exist in the DB
// and that both Chinese and English book titles are written.
// No HTTP requests are made in this phase — titles come directly from the spec.
func (s *BibleScraper) setupBooks() ([]BookMeta, error) {
	log.Println("Phase 1: Setting up Books from spec...")

	var books []BookMeta
	var mu sync.Mutex
	var wg sync.WaitGroup

	for i := 0; i < len(s.Spec.ZH); i++ {
		wg.Add(1)
		go func(idx int) {
			defer wg.Done()

			bookID, err := s.Repo.GetOrCreateBook(idx + 1)
			if err != nil {
				log.Printf("Phase 1: failed to get/create book %d: %v", idx+1, err)
				return
			}

			zhTitle := s.Spec.ZH[idx].NameZH
			enTitle := s.Spec.EN[idx].NameEN

			if err = s.Repo.UpsertBookContent(bookID, LangChinese, zhTitle); err != nil {
				log.Printf("Phase 1: failed to write ZH title for book %d: %v", idx+1, err)
			}
			if err = s.Repo.UpsertBookContent(bookID, LangEnglish, enTitle); err != nil {
				log.Printf("Phase 1: failed to write EN title for book %d: %v", idx+1, err)
			}

			mu.Lock()
			books = append(books, BookMeta{ID: bookID, Index: idx})
			mu.Unlock()
		}(i)
	}

	wg.Wait()
	sort.Slice(books, func(i, j int) bool { return books[i].Index < books[j].Index })

	if len(books) != len(s.Spec.ZH) {
		return nil, fmt.Errorf("only %d/%d books set up; aborting chapter crawl", len(books), len(s.Spec.ZH))
	}
	log.Printf("Phase 1 complete: %d books ready.", len(books))
	return books, nil
}

// chapterContext carries validated per-request crawl parameters.
type chapterContext struct {
	bookID    uuid.UUID
	bookIndex int // 0-based spec index
	chapSort  int // 1-based chapter number within the book
	lang      string
	maxVerses int // spec verse count for this book+chapter+language
}

// parseChapterContext validates all Colly context values before any DB writes.
func parseChapterContext(ctx *colly.Context) (chapterContext, error) {
	rawBookID := strings.TrimSpace(ctx.Get("bookID"))
	if rawBookID == "" {
		return chapterContext{}, fmt.Errorf("missing bookID in request context")
	}
	bookID, err := uuid.Parse(rawBookID)
	if err != nil {
		return chapterContext{}, fmt.Errorf("invalid bookID %q: %w", rawBookID, err)
	}

	bookIndex, err := strconv.Atoi(strings.TrimSpace(ctx.Get("bookIndex")))
	if err != nil || bookIndex < 0 {
		return chapterContext{}, fmt.Errorf("invalid bookIndex %q", ctx.Get("bookIndex"))
	}

	chapSort, err := strconv.Atoi(strings.TrimSpace(ctx.Get("chapSort")))
	if err != nil || chapSort <= 0 {
		return chapterContext{}, fmt.Errorf("invalid chapSort %q", ctx.Get("chapSort"))
	}

	maxVerses, err := strconv.Atoi(strings.TrimSpace(ctx.Get("maxVerses")))
	if err != nil || maxVerses <= 0 {
		return chapterContext{}, fmt.Errorf("invalid maxVerses %q", ctx.Get("maxVerses"))
	}

	lang := strings.TrimSpace(ctx.Get("lang"))
	if lang != LangChinese && lang != LangEnglish {
		return chapterContext{}, fmt.Errorf("unsupported language %q", lang)
	}

	return chapterContext{
		bookID:    bookID,
		bookIndex: bookIndex,
		chapSort:  chapSort,
		lang:      lang,
		maxVerses: maxVerses,
	}, nil
}

// crawlChapters asynchronously crawls every chapter page in both languages.
// The spec drives which chapters exist and how many verses each should have.
func (s *BibleScraper) crawlChapters(books []BookMeta) {
	log.Println("Phase 2: Crawling Chapters...")

	c := s.C.Clone()

	c.OnResponse(func(r *colly.Response) {
		cc, err := parseChapterContext(r.Ctx)
		if err != nil {
			log.Printf("Skipping response with invalid context (url=%s): %v",
				r.Request.URL.String(), err)
			return
		}

		var body string
		if cc.lang == LangChinese {
			body, err = utils.Big5ToUTF8(r.Body)
		} else {
			body = string(r.Body)
		}
		if err != nil {
			log.Printf("Encoding error lang=%s chap=%d: %v", cc.lang, cc.chapSort, err)
			return
		}

		chapID, err := s.Repo.GetOrCreateChapter(cc.bookID, cc.chapSort)
		if err != nil {
			log.Printf("DB error creating chapter (bookID=%s chap=%d): %v",
				cc.bookID, cc.chapSort, err)
			return
		}

		chapTitle := fmt.Sprintf("第 %d 章", cc.chapSort)
		if cc.lang == LangEnglish {
			chapTitle = fmt.Sprintf("Chapter %d", cc.chapSort)
		}
		if err = s.Repo.UpsertChapterContent(chapID, cc.lang, chapTitle); err != nil {
			log.Printf("DB error saving chapter content (chapID=%s lang=%s): %v",
				chapID, cc.lang, err)
		}

		doc, err := goquery.NewDocumentFromReader(strings.NewReader(body))
		if err != nil {
			log.Printf("GoQuery parse error (bookID=%s chap=%d): %v",
				cc.bookID, cc.chapSort, err)
			return
		}

		doc.Find("script, style, a").Remove()

		foundVerses := 0
		doc.Find("ol li").Each(func(i int, sel *goquery.Selection) {
			verseNum := i + 1
			if valStr, exists := sel.Attr("value"); exists {
				if parsed, parseErr := strconv.Atoi(strings.TrimSpace(valStr)); parseErr == nil && parsed > 0 {
					verseNum = parsed
				} else {
					log.Printf("Invalid verse value %q, using fallback %d", valStr, verseNum)
				}
			}

			// Spec guard: reject verse numbers beyond what the JSON spec defines.
			// This prevents creating orphan sections from HTML artifacts or
			// cross-translation versification mismatches.
			if verseNum > cc.maxVerses {
				log.Printf("Skipping verse %d: exceeds spec max=%d (book=%d chap=%d lang=%s)",
					verseNum, cc.maxVerses, cc.bookIndex+1, cc.chapSort, cc.lang)
				return
			}

			content := utils.CleanText(sel.Text())
			if content == "" {
				return
			}

			if saveErr := s.saveVerse(cc.bookID, chapID, verseNum, cc.lang, content); saveErr != nil {
				log.Printf("Failed to save verse (book=%d chap=%d verse=%d lang=%s): %v",
					cc.bookIndex+1, cc.chapSort, verseNum, cc.lang, saveErr)
				return
			}
			foundVerses++
		})

		if foundVerses == 0 {
			log.Printf("Warning: no verses found (book=%d chap=%d lang=%s)",
				cc.bookIndex+1, cc.chapSort, cc.lang)
		}
	})

	for _, book := range books {
		if book.ID == uuid.Nil {
			log.Printf("Skipping book with nil ID (index=%d)", book.Index)
			continue
		}

		zhBookSpec := s.Spec.ZH[book.Index]
		enBookSpec := s.Spec.EN[book.Index]

		for chap := 1; chap <= zhBookSpec.TotalChapters; chap++ {
			globalChap := s.globalChapStarts[book.Index] + chap - 1

			zhVerseCount, err := zhBookSpec.VerseCount(chap)
			if err != nil {
				log.Printf("Spec error ZH book=%d chap=%d: %v", book.Index+1, chap, err)
				continue
			}
			enVerseCount, err := enBookSpec.VerseCount(chap)
			if err != nil {
				log.Printf("Spec error EN book=%d chap=%d: %v", book.Index+1, chap, err)
				continue
			}

			// Queue Chinese (和合本) request using the URL template from config.
			// SourceZHURL contains %d which is replaced with the global chapter index.
			ctxZH := colly.NewContext()
			ctxZH.Put("bookID", book.ID.String())
			ctxZH.Put("bookIndex", strconv.Itoa(book.Index))
			ctxZH.Put("chapSort", strconv.Itoa(chap))
			ctxZH.Put("lang", LangChinese)
			ctxZH.Put("maxVerses", strconv.Itoa(zhVerseCount))
			urlCUV := fmt.Sprintf(s.Cfg.SourceZHURL, globalChap)
			if err := c.Request("GET", urlCUV, nil, ctxZH, nil); err != nil {
				log.Printf("Failed to queue ZH request (book=%d chap=%d): %v",
					book.Index+1, chap, err)
			}

			// Queue English (BBE) request using the URL template from config.
			// SourceENURL contains %d which is replaced with the global chapter index.
			ctxEN := colly.NewContext()
			ctxEN.Put("bookID", book.ID.String())
			ctxEN.Put("bookIndex", strconv.Itoa(book.Index))
			ctxEN.Put("chapSort", strconv.Itoa(chap))
			ctxEN.Put("lang", LangEnglish)
			ctxEN.Put("maxVerses", strconv.Itoa(enVerseCount))
			urlBBE := fmt.Sprintf(s.Cfg.SourceENURL, globalChap)
			if err := c.Request("GET", urlBBE, nil, ctxEN, nil); err != nil {
				log.Printf("Failed to queue EN request (book=%d chap=%d): %v",
					book.Index+1, chap, err)
			}
		}
	}

	c.Wait()
	log.Println("Phase 2 complete.")
}

// saveVerse persists one verse's structural row and localized content.
func (s *BibleScraper) saveVerse(bookID, chapID uuid.UUID, verseNum int, lang, content string) error {
	if verseNum <= 0 {
		return fmt.Errorf("invalid verse number %d", verseNum)
	}
	normalizedContent := utils.CleanText(content)
	if normalizedContent == "" {
		return fmt.Errorf("empty verse content")
	}

	verseTitle := fmt.Sprintf("第%d節", verseNum)
	if lang == LangEnglish {
		verseTitle = fmt.Sprintf("verse %d", verseNum)
	}

	secID, err := s.Repo.GetOrCreateSection(bookID, chapID, verseNum)
	if err != nil {
		return fmt.Errorf("get/create section %d: %w", verseNum, err)
	}

	if err = s.Repo.UpsertSectionContent(secID, lang, verseTitle, normalizedContent); err != nil {
		return fmt.Errorf("upsert section content %d: %w", verseNum, err)
	}
	return nil
}
