// cmd/biblecom-crawler — entry point for the bible.com HTML crawler.
//
// This command crawls bible.com for two translations in parallel:
//
//   - Chinese: CUNP-上帝 (version ID 414)
//   - English: NIV       (version ID 111)
//
// All scraped verses (including optional section sub_titles) are written to two
// JSON files rather than directly to PostgreSQL, following the same checkpoint
// philosophy as cmd/youversion-crawler. The JSON files can be inspected,
// diffed, and imported to the database independently.
//
// Usage:
//
//	go run cmd/biblecom-crawler/main.go
//
// Required files (must exist before running):
//
//	bible_books_zh.json   — used for chapter counts
//	bible_books_en.json   — used for chapter counts (same versification)
//
// Environment variables (see .env.example for full list):
//
//	BIBLECOM_ZH_BASE_URL        base URL for CUNP pages
//	BIBLECOM_EN_BASE_URL        base URL for NIV pages
//	BIBLECOM_ZH_VERSION_SUFFIX  URL suffix for CUNP (with URL-encoded 上帝)
//	BIBLECOM_EN_VERSION_SUFFIX  URL suffix for NIV
//	BIBLECOM_WORKERS            worker goroutine count (default 5)
//	BIBLECOM_RATE_LIMIT_RPS     max requests per second (default 2.0)
//	BIBLECOM_TIMEOUT_SEC        per-request HTTP timeout (default 30)
//	BIBLECOM_OUTPUT_ZH          output JSON file path for Chinese
//	BIBLECOM_OUTPUT_EN          output JSON file path for English
package main

import (
	"context"
	"fmt"
	"log"
	"net/url"
	"os"
	"os/signal"
	"regexp"
	"strings"
	"syscall"

	"bible-crawler/internal/biblecom"
	"bible-crawler/internal/config"
)

func main() {
	log.SetFlags(log.Ldate | log.Ltime | log.Lmsgprefix)
	log.SetPrefix("[biblecom-crawler] ")

	cfg := config.Load()

	// Validate required configuration before starting any network activity
	// so the operator gets an immediate, actionable error message.
	if err := validateConfig(cfg); err != nil {
		log.Fatalf("configuration error: %v", err)
	}

	// Load the Bible spec (chapter counts) from the existing JSON spec files.
	// These files are generated by cmd/spec-builder and must be present.
	specBooks, err := biblecom.LoadSpec(
		"bible_books_zh.json",
		"bible_books_en.json",
	)
	if err != nil {
		log.Fatalf("load spec: %v", err)
	}

	scraper := biblecom.NewBibleComScraper(cfg, specBooks)

	// Install a signal handler so Ctrl-C triggers a graceful shutdown:
	// workers finish their current HTTP request before stopping, and
	// partial results are written to disk.
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	zhOut, enOut, err := scraper.Run(ctx)
	if err != nil {
		log.Fatalf("crawl failed: %v", err)
	}

	log.Printf("Writing output files…")
	if err := biblecom.WriteOutputFiles(
		zhOut, enOut,
		cfg.BibleComOutputZH, cfg.BibleComOutputEN,
	); err != nil {
		log.Fatalf("write output: %v", err)
	}

	// Count verses for the completion summary.
	zhVerses, enVerses := countVerses(zhOut), countVerses(enOut)
	log.Printf("Done — ZH: %d verses in %d books | EN: %d verses in %d books",
		zhVerses, len(zhOut.Books), enVerses, len(enOut.Books))
}

// validateConfig checks that every required BibleCom configuration field has
// been set, that URL fields use HTTPS and target bible.com, and that numeric
// tuning parameters are within safe operational bounds. It returns a
// descriptive error for the first failing check, making it easy for operators
// to know exactly what to fix in their .env file.
func validateConfig(cfg *config.Config) error {
	type check struct {
		name  string
		value string
	}
	required := []check{
		{"BIBLECOM_ZH_BASE_URL", cfg.BibleComZHBaseURL},
		{"BIBLECOM_EN_BASE_URL", cfg.BibleComENBaseURL},
		{"BIBLECOM_ZH_VERSION_SUFFIX", cfg.BibleComZHVersionSuffix},
		{"BIBLECOM_EN_VERSION_SUFFIX", cfg.BibleComENVersionSuffix},
		{"BIBLECOM_OUTPUT_ZH", cfg.BibleComOutputZH},
		{"BIBLECOM_OUTPUT_EN", cfg.BibleComOutputEN},
	}
	for _, c := range required {
		if c.value == "" {
			return fmt.Errorf("%s must not be empty; check your .env file", c.name)
		}
	}

	// Enforce HTTPS + bible.com host on base URLs to prevent accidental SSRF
	// (CWE-918: Server-Side Request Forgery) or TLS downgrade (CWE-319:
	// Cleartext Transmission of Sensitive Information) from a misconfigured or
	// tampered env var.
	for _, f := range []struct{ name, val string }{
		{"BIBLECOM_ZH_BASE_URL", cfg.BibleComZHBaseURL},
		{"BIBLECOM_EN_BASE_URL", cfg.BibleComENBaseURL},
	} {
		u, err := url.Parse(f.val)
		if err != nil || u.Scheme != "https" || !strings.HasSuffix(u.Host, "bible.com") {
			return fmt.Errorf("%s must be an https://www.bible.com/... URL, got %q", f.name, f.val)
		}
	}

	// Validate version suffixes (CWE-20, CWE-601): the suffix is interpolated
	// directly into every chapter URL path segment via fmt.Sprintf in buildURL.
	// Without validation a tampered env var could inject query-string characters
	// ('?', '#') or path separators ('/') that cross URL component boundaries,
	// altering all 2,378 request URLs silently.
	//
	// Allowed: [A-Za-z0-9%_.~-]+ — covers the current defaults:
	//   CUNP-%E4%B8%8A%E5%B8%9D  (percent-encoded 上帝)
	//   NIV
	// Blocked: '?', '#', '/', '\r', '\n', whitespace.
	validVersionSuffix := regexp.MustCompile(`^[A-Za-z0-9%_.~-]+$`)
	for _, f := range []struct{ name, val string }{
		{"BIBLECOM_ZH_VERSION_SUFFIX", cfg.BibleComZHVersionSuffix},
		{"BIBLECOM_EN_VERSION_SUFFIX", cfg.BibleComENVersionSuffix},
	} {
		if !validVersionSuffix.MatchString(f.val) {
			return fmt.Errorf(
				"%s %q contains characters not allowed in a URL path segment "+
					"(only [A-Za-z0-9%%_.~-] are permitted)",
				f.name, f.val)
		}
	}

	// Bounds-check numeric tuning parameters to catch silent failure modes:
	//   workers=0  → no goroutines launched, empty output with no error
	//   rps=0      → rate.Limiter blocks forever (deadlock)
	//   timeout<5s → every request times out immediately
	if cfg.BibleComWorkers < 1 || cfg.BibleComWorkers > 50 {
		return fmt.Errorf("BIBLECOM_WORKERS must be 1–50, got %d", cfg.BibleComWorkers)
	}
	if cfg.BibleComRateLimitRPS <= 0 || cfg.BibleComRateLimitRPS > 20 {
		return fmt.Errorf("BIBLECOM_RATE_LIMIT_RPS must be 0.1–20.0, got %g", cfg.BibleComRateLimitRPS)
	}
	if cfg.BibleComTimeoutSec < 5 || cfg.BibleComTimeoutSec > 120 {
		return fmt.Errorf("BIBLECOM_TIMEOUT_SEC must be 5–120, got %d", cfg.BibleComTimeoutSec)
	}
	return nil
}

// countVerses returns the total verse count across all books and chapters in
// an OutputFile, used for the completion summary log line.
func countVerses(out *biblecom.OutputFile) int {
	total := 0
	for _, book := range out.Books {
		for _, ch := range book.Chapters {
			total += len(ch.Verses)
		}
	}
	return total
}

