// Package spec loads the two language-specific Bible JSON specification files
// and exposes per-book, per-chapter verse counts. Both commands (crawler,
// spec-builder) use this package so verse counts are always data-driven
// with no hard-coded numbers in application logic.
//
// File layout:
//
//	bible_books_zh.json — Chinese 和合本 (CUV): only Chinese name fields.
//	bible_books_en.json — English BBE:           only English name fields.
//
// Both files share the same verses_per_chapter map structure, but the verse
// counts may differ for chapters where CUV and BBE draw boundaries differently
// (versification differences, e.g. Lev ch5/ch6).
package spec

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
)

// BookSpec is the unified internal representation for one Bible book within one
// language spec. Only the fields relevant to the source language are populated:
//
//	ZH loader sets: Number, TestamentZH, NameZH, TotalChapters, TotalVerses, VersesPerChapter
//	EN loader sets: Number, Testament,   NameEN, TotalChapters, TotalVerses, VersesPerChapter
type BookSpec struct {
	Number           int
	Testament        string         // "OT" or "NT" — set by EN loader
	TestamentZH      string         // "舊約" or "新約" — set by ZH loader
	NameZH           string         // Chinese book name — set by ZH loader
	NameEN           string         // English book name — set by EN loader
	TotalChapters    int
	TotalVerses      int
	VersesPerChapter map[string]int // key "01-[31]" = chapter 1 has 31 verses

	// verseCounts is a lazily-built, chapter-ordered verse count cache.
	// Index 0 = chapter 1. Populated on the first call to VerseCount.
	verseCounts []int
}

// VerseCount returns the number of verses in the given 1-based chapter.
// Results are cached after the first call.
func (b *BookSpec) VerseCount(chapter int) (int, error) {
	if b.verseCounts == nil {
		if err := b.buildVerseCounts(); err != nil {
			return 0, fmt.Errorf("book #%d: %w", b.Number, err)
		}
	}
	if chapter < 1 || chapter > len(b.verseCounts) {
		return 0, fmt.Errorf("book #%d: chapter %d out of range (1–%d)",
			b.Number, chapter, len(b.verseCounts))
	}
	return b.verseCounts[chapter-1], nil
}

// buildVerseCounts parses the "01-[31]"-style map keys into a chapter-ordered
// slice. The numeric prefix before the dash is the 1-based chapter number.
func (b *BookSpec) buildVerseCounts() error {
	type pair struct {
		ch    int
		count int
	}
	pairs := make([]pair, 0, len(b.VersesPerChapter))
	for key, count := range b.VersesPerChapter {
		dashIdx := strings.Index(key, "-")
		if dashIdx < 0 {
			return fmt.Errorf("unexpected verses_per_chapter key %q (want \"NN-[N]\")", key)
		}
		ch, err := strconv.Atoi(key[:dashIdx])
		if err != nil {
			return fmt.Errorf("cannot parse chapter number from key %q: %w", key, err)
		}
		pairs = append(pairs, pair{ch, count})
	}
	sort.Slice(pairs, func(i, j int) bool { return pairs[i].ch < pairs[j].ch })

	b.verseCounts = make([]int, len(pairs))
	for i, p := range pairs {
		b.verseCounts[i] = p.count
	}
	return nil
}

// BibleSpec holds per-language book specs for every book in the crawled Bible.
// ZH[i] and EN[i] describe the same book at each index but may report different
// verse counts where the Chinese 和合本 and English BBE place chapter boundaries
// differently. The total number of books is determined by the spec JSON files.
type BibleSpec struct {
	ZH []*BookSpec // 和合本 (Chinese CUV) — loaded from bible_books_zh.json
	EN []*BookSpec // Basic English Version (BBE) — loaded from bible_books_en.json
}

// ── Internal JSON deserialization shapes ─────────────────────────────────────
// These unexported structs mirror the on-disk JSON format of each file exactly.
// bible_books_zh.json contains only Chinese name fields (name_zh, testament_zh).
// bible_books_en.json contains only English name fields (name_en, testament).

type zhBookJSON struct {
	Number           int            `json:"number"`
	TestamentZH      string         `json:"testament_zh"`
	NameZH           string         `json:"name_zh"`
	TotalChapters    int            `json:"total_chapters"`
	TotalVerses      int            `json:"total_verses"`
	VersesPerChapter map[string]int `json:"verses_per_chapter"`
}

type enBookJSON struct {
	Number           int            `json:"number"`
	Testament        string         `json:"testament"`
	NameEN           string         `json:"name_en"`
	TotalChapters    int            `json:"total_chapters"`
	TotalVerses      int            `json:"total_verses"`
	VersesPerChapter map[string]int `json:"verses_per_chapter"`
}

type zhBibleJSON struct {
	Books []zhBookJSON `json:"books"`
}

type enBibleJSON struct {
	Books []enBookJSON `json:"books"`
}

// Load reads both JSON spec files and returns the combined BibleSpec.
// Both files are generated by cmd/spec-builder and must exist before calling Load.
func Load(zhPath, enPath string) (*BibleSpec, error) {
	zh, err := loadZHBooks(zhPath)
	if err != nil {
		return nil, fmt.Errorf("loading ZH spec from %s: %w", zhPath, err)
	}
	en, err := loadENBooks(enPath)
	if err != nil {
		return nil, fmt.Errorf("loading EN spec from %s: %w", enPath, err)
	}
	if len(zh) == 0 {
		return nil, fmt.Errorf("ZH spec: no books found in %s", zhPath)
	}
	if len(zh) != len(en) {
		return nil, fmt.Errorf("ZH and EN specs have different book counts: ZH=%d EN=%d", len(zh), len(en))
	}
	return &BibleSpec{ZH: zh, EN: en}, nil
}

// loadZHBooks reads bible_books_zh.json and populates the Chinese name fields
// (NameZH, TestamentZH) of each returned BookSpec.
func loadZHBooks(path string) ([]*BookSpec, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var doc zhBibleJSON
	if err := json.Unmarshal(raw, &doc); err != nil {
		return nil, fmt.Errorf("JSON parse error: %w", err)
	}
	books := make([]*BookSpec, len(doc.Books))
	for i, b := range doc.Books {
		books[i] = &BookSpec{
			Number:           b.Number,
			TestamentZH:      b.TestamentZH,
			NameZH:           b.NameZH,
			TotalChapters:    b.TotalChapters,
			TotalVerses:      b.TotalVerses,
			VersesPerChapter: b.VersesPerChapter,
		}
	}
	return books, nil
}

// loadENBooks reads bible_books_en.json and populates the English name fields
// (NameEN, Testament) of each returned BookSpec.
func loadENBooks(path string) ([]*BookSpec, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var doc enBibleJSON
	if err := json.Unmarshal(raw, &doc); err != nil {
		return nil, fmt.Errorf("JSON parse error: %w", err)
	}
	books := make([]*BookSpec, len(doc.Books))
	for i, b := range doc.Books {
		books[i] = &BookSpec{
			Number:           b.Number,
			Testament:        b.Testament,
			NameEN:           b.NameEN,
			TotalChapters:    b.TotalChapters,
			TotalVerses:      b.TotalVerses,
			VersesPerChapter: b.VersesPerChapter,
		}
	}
	return books, nil
}

// GlobalChapStarts returns a slice where element i is the 1-based global
// chapter index for book i's first chapter, computed from the ZH spec's
// TotalChapters values. This index is the "chap" URL parameter used by the
// source website (e.g. Genesis starts at 1, Exodus at 51 for the standard canon).
func (s *BibleSpec) GlobalChapStarts() []int {
	starts := make([]int, len(s.ZH))
	offset := 1
	for i, book := range s.ZH {
		starts[i] = offset
		offset += book.TotalChapters
	}
	return starts
}
